name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
jobs:

  build:
  
    strategy:
    
     matrix:
      goos: [windows, linux]
      goarch: [amd64]
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Windows
      if: matrix.goos == 'windows'
      run: |
           go get golang.org/x/sys@v0.0.0-20191026070338-33540a1f6037
        
    - name: Build
      run: go build -v ./...
  
